consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  BottlePayload:
    description: BottlePayload is the type used
    example:
      name: ti
      rating: 1
      vintage: 2818
    properties:
      name:
        description: Name of bottle
        example: ti
        minLength: 2
        type: string
      rating:
        description: Critic's rating of bottle
        example: 1
        maximum: 5
        minimum: 1
        type: integer
      vintage:
        description: Vintage of bottle
        example: 2818
        minimum: 1900
        type: integer
    required:
    - name
    - vintage
    - rating
    title: BottlePayload
    type: object
  bottle:
    description: bottle media type (default view)
    example:
      ID: 6.438311e+18
      name: p6
      rating: 3
      vintage: 2144
    properties:
      ID:
        description: Unique bottle ID
        example: 6.438311e+18
        format: int64
        type: integer
      name:
        description: Name of bottle
        example: p6
        minLength: 2
        type: string
      rating:
        description: Critic's rating of bottle
        example: 3
        maximum: 5
        minimum: 1
        type: integer
      vintage:
        description: Vintage of bottle
        example: 2144
        minimum: 1900
        type: integer
    required:
    - ID
    - name
    - vintage
    - rating
    title: 'Mediatype identifier: application/vnd.gophercon.goa.bottle; view=default'
    type: object
host: localhost:8080
info:
  description: The Wine Review Service
  version: ""
paths:
  /bottles/:
    post:
      description: creates a bottle
      operationId: bottle#create
      parameters:
      - description: BottlePayload is the type used
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/BottlePayload'
      responses:
        "201":
          description: Created
      summary: create bottle
      tags:
      - bottle
  /bottles/{id}:
    get:
      description: shows a bottle
      operationId: bottle#show
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/vnd.gophercon.goa.bottle
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bottle'
      summary: show bottle
      tags:
      - bottle
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Created:
    description: Created
swagger: "2.0"
