// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cellar": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/WineReviewGoa/design
// --out=$(GOPATH)/src/github.com/WineReviewGoa
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// BottleHref returns the resource href.
func BottleHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/bottles/%v", paramid)
}
